'use client'
import { SnippetInterface} from '../models/snippet'
import SnippetActionButtons from './SnippetActionButtons'
import CodeBlock from './CodeBlock'

interface relatedSnippetProps{
    snippet: SnippetInterface,
    onClick : any,
    className?: string
}
export default function RelatedSnippetPreview (props: relatedSnippetProps) {
    
    const handleOnclick = () => {
      props.onClick(props.snippet.query)
    }

    return ( 
        <button className={props.className ?? ""} onClick={handleOnclick}>
          <div className='bg-slate-950 h-[350px] w-[400px] rounded-xl border-neutral-400 border-px flex
          justify-center items-top p-5 flex-col max-w-2xl fadeinComponent'>
    
            <div className='flex flex-col items-center justify-between'>
              <label className='text-white align-middle text-lg font-semibold' >{props.snippet.name}</label>
              <label className='text-white text-opacity-65 text text-xs'>generated by {props.snippet.generatedby}</label>
            </div>
            <div className='overflow-auto flex h-full text-xs'>
              <CodeBlock value={props.snippet.snippet}/>
            </div>
          </div> 
        </button>
      )
}