'use client'
import Markdown from 'react-markdown'
import CodeBlock from './CodeBlock'
import SnippetActionButtons from './SnippetActionButtons'
import { SnippetInterface } from '../models/snippet'
import '@/app/styles/animations.css'

interface snippetPreviewProps {
  snippet: SnippetInterface | undefined,
  className?: string    
}

export default function SnippetPreview (props: snippetPreviewProps) {

  return ( props.snippet != undefined ?(
    <div className={props.className ?? ""}>
      <div className='bg-slate-950 min-h-64 min-w-64 rounded-xl border-neutral-400 border-px flex
      justify-center items-top p-5 flex-col max-w-2xl max-h-[500px] max-w-[600px] fadeinComponent'>

        <div className='flex flex-row items-center justify-between'>
          <label className='text-white align-middle font-semibold' >{props.snippet.name}</label>
          <SnippetActionButtons snippet={props.snippet} />
        </div>
        <div>
          <label className='text-white text-opacity-65 text text-xs'>Generated by {props.snippet.generatedby}</label>
        </div>
        <div className='overflow-auto flex h-full'>
          <CodeBlock value={props.snippet.snippet}/>
        </div>
      </div> 
    </div>
    ) : null
  )
}

